# From https://github.com/cs50/ide/blob/main/.github/workflows/main.yml
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          tags: oliveman/csprimer-ide:${{ github.sha }},oliveman/csprimer-ide:develop
          cache-from: type=registry,ref=oliveman/csprimer-ide:buildcache-develop
          cache-to: type=registry,ref=oliveman/csprimer-ide:buildcache-develop,mode=max
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/image.tar
  
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - name: Load image
        run: docker load -i /tmp/image.tar

      - name: Log into GitHub Packages
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          docker tag oliveman/csprimer-ide:${{ github.sha }} ghcr.io/lisgar-csprimer/ide:develop
          docker push ghcr.io/lisgar-csprimer/ide:develop
